JavaScriptPracticeNotebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("js_Sketch.urls")),
    path('account/', include("account.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path
from .views import signup, ajax_reg, signin, signout, profile, users, confirm_user, deactivate_user, \
    delete_feedback_by_user, admin_feedback_list, delete_feedback_totally, ignore_feedback, feedback_answer

urlpatterns = [
    # path('', index),
    path('signup', signup),
    path('signin', signin),
    path('logout', signout),
    path('ajax_reg', ajax_reg),
    path('profile', profile),
    path('users', users),
    path('admin_feedback_list', admin_feedback_list),
    path('confirm_user/<int:user_id>', confirm_user),
    path('deactivate_user/<int:user_id>', deactivate_user),
    path('detete_feedback/<int:feedback_id>', delete_feedback_by_user),
    path('ignore_feedback/<int:feedback_id>', ignore_feedback),
    path('feedback_answer/<int:feedback_id>', feedback_answer),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User


class Feedback(models.Model):

    class StatusChoice(models.TextChoices):
        PENDING = 'Pending'
        ANSWERED = 'Answered'
        DELETED_BY_USER = 'Deleted by user'
        IGNORED = 'Ignored'

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=32)
    content = models.TextField(max_length=512)
    answer = models.TextField(max_length=512, blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=32, choices=StatusChoice.choices, default=StatusChoice.PENDING)

    class Meta:
        ordering = ['timestamp']

    def __str__(self):
        return f'{self.id}. {self.title} ({self.user.username}/{self.timestamp})'


class Usersetup(models.Model):
    registered_user_daily_posts = models.IntegerField(default=20)
    registered_user_feedback_limit = models.IntegerField(default=10)
    unregistered_user_daily_posts = models.IntegerField(default=0)
    unregistered_user_feedback_limit = models.IntegerField(default=2)

    def __str__(self):
        return 'USER_SETTINGS'

js_Sketch/models.py
from django.db import models
from django.contrib.auth.models import User


class Language(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        return super(Language, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Problem(models.Model):
    title = models.CharField(max_length=64)
    problemtext = models.TextField(max_length=1024)
    solutioncode = models.TextField(max_length=1024)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}. {self.title}'

    class Meta:
        ordering = ["-id", ]

templates/sketch/add_language.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
    Tasks
{% endblock title %}
{% block content %}



   <form method="post" enctype="multipart/form-data">{% csrf_token %}
    {% for field in form%}
        <h4>
            {{ field.label_tag }}<br>
            {{ field }}
        </h4>
    {% endfor %}
       <style>
            #id_name{
                width: 100%;
            }

       </style>

    <input type='submit' class="btn btn-lg btn-primary" value='Add language' />
</form>

    {% for language in all_languages %}
        <div style="border: 2px dotted black; width: 50%; margin: 5px">
            <a href="/delete_language/{{ language.id }}" class="btn btn-danger">✘</a>
            {{ language.name }}<br>
        </div>
    {% endfor %}

{% endblock content %}

templates/sketch/code_editor.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
    JS Editor
{% endblock title %}
{% block content %}


    <textarea class="codemirror-textarea" id="codemirror-textarea" ></textarea>
    <button class="btn btn-success m-4 w-25" id="run-button">Run</button>
    <div class="resultblock" style="min-height: 300px; width: 100%; background-color: grey; color: ghostwhite"></div>

    <script>
    let basic_text = `<h1>
  Hello world
</h1>

<h4>
  It is your frondend sandbox. Try it.
</h4>

<script>
\tlet arr = [];
  \tfunction func() {
\t\tlet value = 1;
\t\treturn value;
\t}
\talert(func())
\</s` + 'cript>';
    $(".codemirror-textarea").text(basic_text);

    let myCodeMirror = CodeMirror.fromTextArea($('#codemirror-textarea')[0], {
        mode:  "htmlmixed",
        lineNumbers: true,
       theme: 'material-darker',
        autoCloseTags: true,

    });
    $('#run-button').click(function () {
         {#myCodeMirror.toTextArea();#}
        let code = $('.CodeMirror-line').text();
        $(".resultblock").html(code);
    });


    </script>

    <style>

    </style>
{% endblock content %}

templates/sketch/codemirrortest.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
    JS Editor
{% endblock title %}
{% block content %}


    <textarea class="codemirror-textarea" id="codemirror-textarea" ></textarea>
    <button class="btn btn-success m-4 w-25" id="run-button">Run</button>
    <div class="resultblock" style="min-height: 300px; width: 100%; background-color: grey; color: ghostwhite"></div>

    <script>
    let basic_text = `<h1>
  Hello world
</h1>

<h4>
  It is your frondend sandbox. Try it.
</h4>

<script>
\tlet arr = [];
  \tfunction func() {
\t\tlet value = 1;
\t\treturn value;
\t}
\talert(func())
\</s` + 'cript>';
    $(".codemirror-textarea").text(basic_text);

    let myCodeMirror = CodeMirror.fromTextArea($('#codemirror-textarea')[0], {
        mode:  "htmlmixed",
        lineNumbers: true,
       theme: 'material-darker',
        autoCloseTags: true,

    });
    $('#run-button').click(function () {
         {#myCodeMirror.toTextArea();#}
        let code = $('.CodeMirror-line').text();
        $(".resultblock").html(code);
    });


    </script>

    <style>

    </style>
{% endblock content %}

templates/sketch/edit_problem.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
    Edit problem
{% endblock title %}
{% block content %}

    <form class="" id="form-for-code" method="post" enctype="multipart/form-data">{% csrf_token %}
{% for field in form %}
    <h4>
        {{ field.label_tag }}
        <p>{{ field }}</p>
    </h4>
{% endfor %}
       <style>
            #id_title{
                width: 100%;
            }
            #id_problemtext{
                width: 100%;
            }



       </style>


    <input type='submit' class="btn btn-lg btn-primary run-button" value='Edit problem' />

</form>

    

    <script>
        $('#id_problemtext').attr("rows", 5);
        $('#id_solutioncode').addClass("codemirror-textarea");
    function codemirror(mode='{{ problem.language.name }}'){
        return CodeMirror.fromTextArea($('.codemirror-textarea')[0], {
            mode: `${mode}`,
            lineNumbers: true,
           theme: 'material-darker',
            autoCloseTags: true,



        });
    };
    let myCodeMirror = codemirror();
    $('.run-button').click(function () {
         myCodeMirror.toTextArea();
    });
    $('#id_language').change(function () {
        myCodeMirror.toTextArea();
        let choice = ($('#id_language').children("option:selected").text());
        if (choice === '---------'){
            choice = 'javascript';
        }else if (choice === 'html'){
            choice = 'htmlmixed';
        }
        myCodeMirror = codemirror(choice);

    });
    </script>
{% endblock content %}

templates/sketch/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
    Main
{% endblock title %}
{% block content %}

    <h1 class="cover-heading">Welcome</h1>
    <p class="lead">It is your helper in coding life. Please check out more information about the website below:</p>


    <div class="accordion" id="accordionExample">
        <div class="card">
            <div class="card-header bg-dark" id="headingOne">
                <h2 class="mb-0">
                    <button class="btn btn-primary w-100" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Website opportunities
                    </button>
                </h2>
            </div>

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body bg-dark">
                   You can note your code in <a class="text-primary" href="/problems_list"> problems section</a> with different languages. (Only for registered users)
                    <br>
                    <a class="text-primary" href="/js_editor">Front End</a> tranings available without sign up.
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header bg-dark" id="headingTwo">
                <h2 class="mb-0">
                    <button class="btn btn-primary w-100 collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Rules and permissions
                    </button>
                </h2>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                <div class="card-body bg-dark">
                    For unregistered users available 'read-only' content. It is free to use, spectate, enjoy😙
                    <br>
                    You can also <a class="text-danger" href="">sign up</a> for free.
                    As I didn't put a lot of energy into security - registered users should be confirmed by admin manualy.
                    <br>
                    Confirmed and not confirmed users have different permissions (absolute and dayly). It is dynamically
                    changed variables. All restrictions will be shown in corresponding areas.
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header bg-dark" id="headingThree">
                <h2 class="mb-0">
                    <button class="btn btn-primary w-100 collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        Feedback
                    </button>
                </h2>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                <div class="card-body bg-dark">
                    Each registered user can send feedback, improve offers or questions from profile section. <br>
                    Number of new feedback is also limited, depending on user status.
                </div>
            </div>
        </div>
            <div class="card">
            <div class="card-header bg-dark" id="headingFour">
                <h2 class="mb-0">
                    <button class="btn btn-primary w-100 collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                        Privacy policy
                    </button>
                </h2>
            </div>
            <div id="collapseFour" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                <div class="card-body bg-dark">
                    Data collection on this website used only for registration and code submission. <br>
                    It is email, username, password (hashed, without saving raw), feedback to administration and posts with code.
                    <br> If you with to delete your submitted data - please contact Admin via your profile tab.

                </div>
            </div>
        </div>
    </div>



{% endblock content %}

templates/sketch/problems_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
    Tasks
{% endblock title %}
{% block content %}


    <div id="problemslist" class="collapse show multi-collapse mt-2" >
    <form class="form-group" method="GET" action="">
        <input class="form-control" type="text" name="q" placeholder="Search problem" value="{{ request.GET.q }}">
        <input class="btn btn-success m-1" type="submit" value="Search">
    </form><br>
        {% for problem in all_tasks %}

            <div style="border: 2px dotted black; width: 100%; margin: 5px">
                <div class="row m-1">
                    <div class="text-danger col-lg-8 my-1">
                        <a data-toggle="collapse" href="#problem-code-{{ problem.id }}"
                                                 role="button" aria-expanded="false" aria-controls="collapseExample"
                                                 class="btn btn-warning mr-1">{{ problem.title }}</a>
                        ({{ problem.language }}) <span class="text-secondary">/ {{ problem.user.username }}</span>
                    </div>
                    <div class="col-lg-4">
                        {% if user.is_superuser or user == problem.user %}
                            <a class="btn btn-outline-secondary" href="/problem/{{ problem.id }}/edit">Edit</a>
                            <a class="btn btn-outline-danger " href="/problem/{{ problem.id }}/delete">Delete</a>
                        {% endif %}

                    </div>
                </div>

                <div id="problem-code-{{ problem.id }}" class="collapse">{{ problem.problemtext | linebreaks }}
                    <pre>
                <code data-language="{{ problem.language }}">{{ problem.solutioncode }}</code>
            </pre>
                </div>
            </div>
        {% endfor %}
            <div class="pagination">
    <span class="step-links">
        {% if all_tasks.has_previous %}
            <a class="btn btn-sm btn-secondary" href="?{{ page_request_var }}={{ all_tasks.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><</a>
        {% endif %}

        <span class="current">
            Page {{ all_tasks.number }} of {{ all_tasks.paginator.num_pages }}.
        </span>

        {% if all_tasks.has_next %}
            <a class="btn btn-sm btn-secondary" href="?{{ page_request_var }}={{ all_tasks.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">></a>
        {% endif %}
    </span>
    </div><br>
    </div>
    {% if user.is_authenticated %}
        <button class="btn btn-secondary" data-toggle="collapse" data-target=".multi-collapse" role="button" aria-expanded="false" aria-controls="form-for-code problemslist">Add code</button>
        <form class="collapse multi-collapse" id="form-for-code" method="post" enctype="multipart/form-data">{% csrf_token %}
            <small class="text-warning">Your quota for posts today {{ post_quote_left }}/{{ quote }} left</small>
            {% for field in form%}
                <h4>
                    {{ field.label_tag }}
                    <p>{{ field }}</p>
                </h4>
            {% endfor %}
            <style>
                #id_title{
                    width: 100%;
                }
                #id_problemtext{
                    width: 100%;
                }



            </style>


            <input type='submit' class="btn btn-lg btn-primary run-button" value='Create Post' />

        </form>
    {% endif %}

    

    <script>
        $('#id_problemtext').attr("rows", 5);
        $('#id_solutioncode').addClass("codemirror-textarea");
    function codemirror(mode='javascript'){
        return CodeMirror.fromTextArea($('.codemirror-textarea')[0], {
            mode: `${mode}`,
            lineNumbers: true,
           theme: 'material-darker',
            autoCloseTags: true,



        });
    };
    let myCodeMirror = codemirror();
    $('.run-button').click(function () {
         myCodeMirror.toTextArea();
    });
    $('#id_language').change(function () {
        myCodeMirror.toTextArea();
        let choice = ($('#id_language').children("option:selected").text());
        if (choice === '---------'){
            choice = 'javascript';
        }else if (choice === 'html'){
            choice = 'htmlmixed';
        }
        myCodeMirror = codemirror(choice);

    });
    </script>
{% endblock content %}